config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'search/search'
  end
    # admin
  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }
  namespace :admin do
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer
  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations',
    :passwords => 'public/passwords'
  }

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
  get '/customers/contact' => 'public/customers#contact'

  scope module: :public do
    resources :items,only: [:index,:show]
    get 'search' => 'items#search'
    # deviseと衝突してしまうので、オリジナルに変更
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'

  	resource :customers,only: [:edit,:update,:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_many :orders, through: :order_details

  attachment :image

  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true

  def self.search_for(content,method)
    return none if content.blank?
     if method == 'perfect'
       Item.where(name: content)

     elsif method == 'forward'
       Item.where('name LIKE ?', content + '%')

     elsif method == 'backword'
       Item.where('name LIKE ?', '%' + content)
     else
       Item.where('name LIKE ?', '%' + content + '%')
     end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
     @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
     if @item.update(item_params)
       flash[:notice] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash[:alert] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品の新規登録内容に不備があります。"
      render :new
    end

  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price,:is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_index.html.erb
     <table class="table  mb-5">
        <thread>
            <tr>
             <th>商品ID</th>
             <th>商品名</th>
             <th>税抜価格</th>
             <th>ジャンル</th>
             <th>ステータス</th>
            </tr>
         </thread>
        <tbody>
         <% items.each do |item| %>
         <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name,admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
              <p class="text-success ">販売中</p>
             <% else %>
              <p class="text-secondary ">販売停止中</p>
            <% end %>
          </td>
         </tr>
        <% end %>
        </tbody>
    </table>

app/views/admin/items/edit.html.erb
<% provide(:title, "商品編集") %>
<div class="container">
  <h2 class="text-center my-5">商品編集</h2>
  <div class="row">
    <div class="col-8 offset-2 mb-5">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <%= f.label :商品画像, class:"form_label"%>
            <%= attachment_image_tag @item, :image, :size => '300x250'%>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品名, class:"form_label" %>
            <%= f.text_field :name, placeholder:"商品名",class:"form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品説明, class:"form_label" %>
            <%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します",class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :ジャンル, class:"form_label" %>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--",class:"form-select" %>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <%= f.label :税抜価格,class:"form_label" %>
          <%= f.text_field :price,size:"15"%>円
        </div>
        </tr>
        <tr>
        <div class="form-group">
          <%= f.label :販売ステータス,class:"form_label my-3" %>
          <%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active, "販売中",class:"form_label" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中",class:"form_label" %>
          </td>
        </div>
        </tr>
        <tr>
        <div class="form-action d-flex justify-content-around">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
          <%= link_to "商品詳細へ戻る",admin_item_path, class:"btn btn-outline-secondary" %>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<% provide(:title, "商品") %>
<div class="container">
    <div class="row">
        <div class="col-sm-8 px-sm-0 offset-sm-1">
            <h2 class="my-5">商品一覧</h2>
        </div>
        <div class="col-sm-2 px-sm-0 text-right mt-5">

            <%= link_to new_admin_item_path,class:"btn btn btn-outline-secondary" do %>
            <i class="fas fa-plus"></i>

            <% end %>
        </div>
    </div>
    <div class="row">
    　<div class="col-sm-10 offset-1">
        <%= render 'index', items: @items%>
          <%= paginate @items %>
        </div>
    </div>
</div>

app/views/admin/items/new.html.erb
<% provide(:title, "新規商品") %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%=  f.file_field :image %></th
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
          </td>
        </div>
        </tr>
        <tr>
        <div class="form-action">
          <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<% provide(:title, "商品詳細") %>
<div class="container">
  <h2 class="mt-5 text-center">商品詳細</h2>
    <div class="row align-items-center m-5">
      <div class="col-lg text-center mb-5">
        <%= attachment_image_tag @item, :image, :size => '300x250'%>
      </div>
      <div class="col-lg">
          <table class="table">
            <tr>
              <th>商品名</th>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <th>
                  税込価格<br>
                  (税抜き価格)
              </th>
              <td><%= @item.tax_in_price %> (<%= @item.price %>) 円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
                <td>
                     <% if @item.is_active == true %>
                        <p class="text-success ">販売中</p>
                     <% else %>
                        <p class="text-secondary ">販売停止中</p>
                     <% end %>
                </td>
            </tr>
          </table>
          <div class="d-flex justify-content-around">
            <p><%= link_to '編集する', edit_admin_item_path(@item.id), class: 'btn btn-success' %></p>
            <p><%= link_to "商品一覧へ戻る", admin_items_path, class:"btn btn-outline-secondary"%></p>
          </div>
   　　 </div>
  　</div>
 </div>