config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'search/search'
  end
    # admin
  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }
  namespace :admin do
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer
  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations',
    :passwords => 'public/passwords'
  }

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
  get '/customers/contact' => 'public/customers#contact'

  scope module: :public do
    resources :items,only: [:index,:show]
    get 'search' => 'items#search'
    # deviseと衝突してしまうので、オリジナルに変更
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'

  	resource :customers,only: [:edit,:update,:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
       <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
       <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">© 2021 04~ PandaMaguro</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <% if admin_signed_in? %>
        <%= link_to "NaganoCAKE", admin_orders_path, class:"header-title navbar-brand"%>
      <% else %>
        <%= link_to "NaganoCAKE", root_path, class:"header-title navbar-brand"%>
      <% end %>

      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <% if customer_signed_in? %>
          <li class="nav-item active">
           <span class="nav-link text-dark">ようこそ<%= full_name(current_customer)%>さん</span>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", customers_path(current_customer), class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>
          <li class="nav-item ">
            <%= link_to "商品一覧", items_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "カート",cart_items_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_items_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_orders_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
         <% else %>
         <li class="nav-item">
             <%= link_to "about", about_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", items_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_customer_session_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
          <% end %>
        </ul>
      </div>

 </nav>
</header>

app/views/layouts/_search.html.erb
<%= form_with url: admin_search_path, method: :get, local: true do |f| %>
  <div class="d-flex justify-content-end mt-3 mr-5">
    <%= f.text_field :content, placeholder: "\uf002 Search", class: "fa" %>
    <%= f.select :model, options_for_select({"Customer" => "customer","Item" => "item"})%>
    <%= f.select :method, options_for_select({"前方一致" => "forward", "後方一致" => "backword", "部分一致" => "patial"})%>
    <%= f.submit "検索", class:"btn btn-outline-secondary ml-2"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= favicon_link_tag 'favicon.jpeg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/b4a646c6ff.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div id="wrapper">

    <%= render "layouts/header"%>
    <main>
    <% if admin_signed_in?%>
      <%= render "layouts/search"%>
    <% end %>
      <div class="container">
      <div id="flash">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
    </main>


    </div>
  </body>
</html>
    </div>
  </body>
</html>